image: maven:3.5.4-jdk-8

stages:
    - test
    - analyze

unit_test:
    stage: test
    script:
    - mvn clean test
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'

sonar_analyze:
    stage: analyze
    script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true